name: Build and Deploy to Azure Static Web App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # You can change this to your preferred version

      - name: Install dependencies
        run: |
          npm install
          # Add OpenSSL legacy provider for compatibility
          export NODE_OPTIONS=--openssl-legacy-provider

      - name: Build the app
        run: |
          npm run build

      - name: Deploy to Azure Static Web Apps
        uses: azure/static-web-apps-deploy-action@v1.0.0
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          app_location: "/"  # Set this to your app's source location (e.g., '/' or 'src')
          api_location: ""   # Leave empty if you don't have an API
          output_location: "out"  # Set this to the folder where your build output resides (e.g., 'out', 'build', 'dist')
